admin = User.create(:email => 'josh@bcjbeverage.com', :first_name => "Josh", :last_name => "Garner", :password => 'kombucha', :password_confirmation => 'kombucha', :roles => [:admin])

lemon = Flavor.create(:name => 'lemon ginger')
berry = Flavor.create(:name => 'berry black')
mint = Flavor.create(:name => 'mint green')
rose = Flavor.create(:name => 'rose bud')

circulation = ProcessType.create(:name => 'circulation', :sort_order => 0, :category => ProcessType::FERMENTATION)
ventilation = ProcessType.create(:name => 'ventilation', :sort_order => 1, :category => ProcessType::FERMENTATION)
aeration = ProcessType.create(:name => 'aeration', :sort_order => 2, :secure => true, :category => ProcessType::FERMENTATION)
refrigeration = ProcessType.create(:name => 'refrigeration', :sort_order => 3, :category => ProcessType::FERMENTATION)
carbonation = ProcessType.create(:name => 'carbonation', :sort_order => 4, :category => ProcessType::CARBONATION)
bottling = ProcessType.create(:name => 'bottling', :sort_order => 5, :category => ProcessType::BOTTLING)

PackageType.create(:name => 'half_keg', :capacity => '15.5 gallons', :sort_order => 1)
PackageType.create(:name => 'sixth_keg', :capacity => '5 gallons', :sort_order => 2)
PackageType.create(:name => 'growler', :capacity => '64 oz', :sort_order => 3)
PackageType.create(:name => 'case', :capacity => '12 bottles', :sort_order => 4)
PackageType.create(:name => 'bottle', :capacity => '16 oz', :sort_order => 5)

ferm_1 = Fermenter.create(:flavor_id => lemon.id,:capacity => 250, :position => 1, :state => 1)
ferm_2 = Fermenter.create(:flavor_id => berry.id,:capacity => 250, :position => 2, :state => 1)
ferm_3 = Fermenter.create(:flavor_id => mint.id,:capacity => 250, :position => 3, :state => 1)
ferm_4 = Fermenter.create(:flavor_id => rose.id,:capacity => 250, :position => 4, :state => 0)
ferm_5 = Fermenter.create(:flavor_id => lemon.id,:capacity => 250, :position => 5, :state => 1)
ferm_6 = Fermenter.create(:flavor_id => berry.id,:capacity => 250, :position => 6, :state => 1)
ferm_7 = Fermenter.create(:flavor_id => mint.id,:capacity => 250, :position => 7, :state => 1)
ferm_8 = Fermenter.create(:flavor_id => rose.id,:capacity => 250, :position => 8, :state => 1)
ferm_9 = Fermenter.create(:flavor_id => lemon.id,:capacity => 250, :position => 9, :state => 1)
ferm_10 = Fermenter.create(:flavor_id => berry.id,:capacity => 250, :position => 10, :state => 1)
ferm_11 = Fermenter.create(:flavor_id => mint.id,:capacity => 250, :position => 11, :state => 1)
ferm_12 = Fermenter.create(:flavor_id => rose.id,:capacity => 250, :position => 12, :state => 1)
